### ISSUE TITLE
Range Image

### ISSUE THREAD

**Issue by fengluodb** [PRBonn/nuscenes2kitti#1]
I'm glad to see such great work. My project is developed on top of your RangeNet, and recently I have been adding support for the nuScenes dataset for our project. Your work has been a great help to me. Do you have more infromation if I want to convert the nuScenes's point cloud to range image. For example, 
```yaml
################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  labels: "kitti"
  scans: "kitti"
  max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 3
    fov_down: -25 
    img_prop:
      width: 1024
      height: 64
    img_means: #range,x,y,z,signal
      - 12.12
      - 10.88
      - 0.23
      - -1.04
      - 0.21
    img_stds: #range,x,y,z,signal
      - 12.32
      - 11.47
      - 6.91
      - 0.86
      - 0.16
```

And, if I convert the nuscenes to kitti format, how can I sumbit the test result. Can you give me the answer. Thank you very much.
